class OttPlatFormExc{

public static void main(String[] abx){
	String movies[]={"MAJESTIC","NINAGOSKARA","KITTY","KARIYA","LAALI HAADU","NEENADERE ISTA","KUSHALAVE KSHAMAVE","NAMMA PRITHIYA RAMU","LANKESH PATRIKE","ANNAVRU","DHARMA","DARSHAN","BHAGAWAN","KALASIPALYA","SARDARA","AYYA","SHASTRI","SWAMY","MANDYA","SUNTARAGALI","DATTHA","THANGIGAGI","BHOOPATHI","SNEHANA PREETHINA","ANATHARU"};
	HotStar star=new HotStar();
	star.getMovies(movies);
	System.out.println(movies);
}

}